version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 3
    groups:
      development-dependencies:
        applies-to: version-updates
        patterns: 
          - "@types/*"
          - "eslint*"
          - "prettier*" 
          - "vitest*"
          - "husky"
          - "@testing-library/*"
      production-dependencies:
        applies-to: version-updates
        patterns:
          - "react*"
          - "@stripe/*"
          - "@supabase/*"
          - "lucide-react" 