name = "chamber-connect"
compatibility_date = "2025-01-27"
pages_build_output_dir = "./dist"

# Default environment variables (preview environment)
[vars]
NODE_ENV = "development"
VITE_APP_ENV = "preview"

# Preview environment (dev/staging branches)
[env.preview.vars]
NODE_ENV = "development"
VITE_APP_ENV = "preview"

# Production environment (master branch)
[env.production.vars]
NODE_ENV = "production"
VITE_APP_ENV = "production"

# Environment-specific variables to set in Cloudflare Dashboard:
# 
# PREVIEW Environment (dev/staging branches):
#   VITE_SUPABASE_URL=https://[dev-ref].supabase.co
#   VITE_SUPABASE_ANON_KEY=eyJ[dev-anon-key]
#   VITE_STRIPE_PUBLISHABLE_KEY=pk_test_[test-key]
#
# PRODUCTION Environment (master branch):
#   VITE_SUPABASE_URL=https://[prod-ref].supabase.co
#   VITE_SUPABASE_ANON_KEY=eyJ[prod-anon-key]
#   VITE_STRIPE_PUBLISHABLE_KEY=pk_live_[live-key] 