name = "chamber-connect"
compatibility_date = "2025-01-27"
pages_build_output_dir = "./dist"

# Default environment variables
[vars]
NODE_ENV = "development"
VITE_APP_ENV = "development"

[env.development.vars]
NODE_ENV = "development"
VITE_APP_ENV = "development"

[env.staging.vars]
NODE_ENV = "staging"
VITE_APP_ENV = "staging"

[env.production.vars]
NODE_ENV = "production"
VITE_APP_ENV = "production"

# Environment-specific variables to set in Cloudflare Dashboard:
# 
# For chamber-connect-dev:
#   VITE_SUPABASE_URL=https://[dev-ref].supabase.co
#   VITE_SUPABASE_ANON_KEY=eyJ[dev-anon-key]
#   VITE_STRIPE_PUBLISHABLE_KEY=pk_test_[test-key]
#
# For chamber-connect-staging:
#   VITE_SUPABASE_URL=https://[staging-ref].supabase.co
#   VITE_SUPABASE_ANON_KEY=eyJ[staging-anon-key]
#   VITE_STRIPE_PUBLISHABLE_KEY=pk_test_[test-key]
#
# For chamber-connect (production):
#   VITE_SUPABASE_URL=https://[prod-ref].supabase.co
#   VITE_SUPABASE_ANON_KEY=eyJ[prod-anon-key]
#   VITE_STRIPE_PUBLISHABLE_KEY=pk_live_[live-key] 